### ISSUE TITLE
Error accessing Packages v8.1.0

### ISSUE THREAD

**Issue by jasteele12** [ExchangeCore/concrete5-Developer-Tools#3]
Just installed 8.1.0 and this package, nothing else added.  When clicking on Packages from the Developer Tools in the dashboard I get this error message:

An unexpected error occurred.
Cannot access protected property Concrete\Core\Entity\Package::$pkgName

Here's what showed up in the error log:
PHP Fatal error:  Cannot access protected property Concrete\Core\Entity\Package::$pkgName in ... 
 packages/ec_dev_tools/single_pages/dashboard/ec_developer_tools/packages.php on line 25

**Comment by jasteele12** [comment]
I believe $package->pkgName, $package->pkgVersion
should be:
$package->getPackageName(), $package->getPackageVersion()

**Comment by jasteele12** [comment]
Is this package dead?

**Comment by joe-meyer** [comment]
Sorry, this just hasn't been a priority honestly. I'll try and get to it this week. You're welcome to open a pull request if you want to help expedite it :)

**Comment by joe-meyer** [comment]
@jasteele12 I think i've got this working now. I didn't spend any time making it pretty again but it should be functional. Hopefully this will get you by until we can spend some more time on it. Thanks for reporting!
